// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechnicalTrainingPlanner.Infrastructure.Persistence;

#nullable disable

namespace TechnicalTrainingPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinOnDuty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobRoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeeAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAvailabilities");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeePersonnelStatus", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonnelStatusCode")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId", "PersonnelStatusCode");

                    b.HasIndex("PersonnelStatusCode");

                    b.ToTable("EmployeePersonnelStatuses");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeeTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CompletedOn")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceReference")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TrainingId");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.InstructorTraining", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("InstructorId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("InstructorTrainings");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisDepartment", b =>
                {
                    b.Property<int>("NeedAnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.HasKey("NeedAnalysisRunId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("NeedAnalysisDepartments");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LookAheadDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PlanningEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlanningStart")
                        .HasColumnType("date");

                    b.Property<string>("ScenarioFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NeedAnalysisRuns");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.OptimizationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSelectedResult")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NeedAnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<string>("ScenarioFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("SolveStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NeedAnalysisRunId")
                        .IsUnique()
                        .HasFilter("\"IsSelectedResult\" = true");

                    b.ToTable("OptimizationRuns");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.PersonnelStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("PersonnelStatuses");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RenewalMonths")
                        .HasColumnType("integer");

                    b.Property<string>("RuleBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OptimizationRunId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingNeedId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingNeedId");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("OptimizationRunId", "TrainingNeedId")
                        .IsUnique();

                    b.ToTable("TrainingAssignments");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingAudienceStatus", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonnelStatusCode")
                        .HasColumnType("text");

                    b.HasKey("TrainingId", "PersonnelStatusCode");

                    b.HasIndex("PersonnelStatusCode");

                    b.ToTable("TrainingAudienceStatuses");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("NeedAnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<string>("NeedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("NeedAnalysisRunId", "EmployeeId", "TrainingId")
                        .IsUnique();

                    b.ToTable("TrainingNeeds");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingPrerequisite", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.Property<int>("PrerequisiteTrainingId")
                        .HasColumnType("integer");

                    b.HasKey("TrainingId", "PrerequisiteTrainingId");

                    b.HasIndex("PrerequisiteTrainingId");

                    b.ToTable("TrainingPrerequisites");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingRequirement", b =>
                {
                    b.Property<int>("JobRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("JobRoleId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingRequirements");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.UnassignedReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("OptimizationRunId")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainingNeedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingNeedId");

                    b.HasIndex("OptimizationRunId", "TrainingNeedId", "ReasonCode")
                        .IsUnique();

                    b.ToTable("UnassignedReasons");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.Employee", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeeAvailability", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeePersonnelStatus", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.PersonnelStatus", "PersonnelStatus")
                        .WithMany()
                        .HasForeignKey("PersonnelStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PersonnelStatus");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.EmployeeTraining", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.InstructorTraining", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisDepartment", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisRun", "NeedAnalysisRun")
                        .WithMany()
                        .HasForeignKey("NeedAnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("NeedAnalysisRun");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.OptimizationRun", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisRun", "NeedAnalysisRun")
                        .WithMany()
                        .HasForeignKey("NeedAnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NeedAnalysisRun");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingAssignment", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.OptimizationRun", "OptimizationRun")
                        .WithMany()
                        .HasForeignKey("OptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.TrainingNeed", "TrainingNeed")
                        .WithMany()
                        .HasForeignKey("TrainingNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptimizationRun");

                    b.Navigation("TrainingNeed");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingAudienceStatus", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.PersonnelStatus", "PersonnelStatus")
                        .WithMany()
                        .HasForeignKey("PersonnelStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonnelStatus");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingNeed", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.NeedAnalysisRun", "NeedAnalysisRun")
                        .WithMany()
                        .HasForeignKey("NeedAnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("NeedAnalysisRun");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingPrerequisite", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "PrerequisiteTraining")
                        .WithMany()
                        .HasForeignKey("PrerequisiteTrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrerequisiteTraining");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingRequirement", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRole");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Instructor");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TechnicalTrainingPlanner.Domain.Entities.UnassignedReason", b =>
                {
                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.OptimizationRun", "OptimizationRun")
                        .WithMany()
                        .HasForeignKey("OptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalTrainingPlanner.Domain.Entities.TrainingNeed", "TrainingNeed")
                        .WithMany()
                        .HasForeignKey("TrainingNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptimizationRun");

                    b.Navigation("TrainingNeed");
                });
#pragma warning restore 612, 618
        }
    }
}
